name: deploy my web server 

on:
  push:
    branches: [master]

jobs:
  Deploy:
      runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Deploy my webserver 1
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY}}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
        runs: | 
          cat << 'EOF' > private_key
          ${{ secrets.EC2_SSH_KEY }}
          EOF
          chmod 600 private_key 
          scp -o StrictHostKeyChecking=no -i private_key index.html ${USERNAME}@${HOSTNAME}:/tmp/
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} "sudo dnf install httpd -y"
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} "sudo systemctl enable --now httpd"
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} "sudo mv /tmp/index.html /var/www/html/index.html"
          
          
          
          
    
